package ir.prdwest.schoolservicemanager
import android.app.*;import android.os.*;import android.content.*;import android.graphics.Color;import android.view.*;import android.widget.*
class MainActivity:Activity(){
 lateinit var db:DatabaseHelper;lateinit var list:LinearLayout;lateinit var ys:Spinner;lateinit var ms:Spinner
 val months=PersianCalendar.months;var start=0;var idx=0
 override fun onCreate(b:Bundle?){super.onCreate(b);window.decorView.layoutDirection=View.LAYOUT_DIRECTION_RTL;db=DatabaseHelper(this);val t=PersianCalendar.today();start=if(t.m<=6)t.y-1 else t.y;idx=if(t.m>=7)t.m-7 else t.m+5;ui()}
 fun text(s:String,z:Float=16f)=TextView(this).apply{text=s;textSize=z;setPadding(12,8,12,8)}
 fun ui(){val r=LinearLayout(this);r.orientation=LinearLayout.VERTICAL;r.setPadding(12,12,12,12);r.addView(text("مدیریت سرویس مدرسه",23f));r.addView(text("سال تحصیلی جاری: "+PersianCalendar.academicYearFor(PersianCalendar.today())));val c=LinearLayout(this);c.orientation=LinearLayout.HORIZONTAL
  ys=Spinner(this);val years=(PersianCalendar.today().y-2..PersianCalendar.today().y+1).map{it.toString()+"-"+(it+1)};ys.adapter=ArrayAdapter(this,android.R.layout.simple_spinner_dropdown_item,years);ys.setSelection(years.indexOf(start.toString()+"-"+(start+1)));ys.onItemSelectedListener=object:AdapterView.OnItemSelectedListener{override fun onNothingSelected(p:AdapterView<*>?){};override fun onItemSelected(p:AdapterView<*>?,v:View?,pos:Int,id:Long){start=years[pos].substringBefore("-").toInt();refresh()}}
  ms=Spinner(this);ms.adapter=ArrayAdapter(this,android.R.layout.simple_spinner_dropdown_item,months);ms.setSelection(idx);ms.onItemSelectedListener=object:AdapterView.OnItemSelectedListener{override fun onNothingSelected(p:AdapterView<*>?){};override fun onItemSelected(p:AdapterView<*>?,v:View?,pos:Int,id:Long){idx=pos;refresh()}}
  c.addView(ys,LinearLayout.LayoutParams(0,-2,1f));c.addView(ms,LinearLayout.LayoutParams(0,-2,1f));r.addView(c)
  r.addView(Button(this).apply{text="+ افزودن بچه جدید";setOnClickListener{add()}});r.addView(Button(this).apply{text="پشتیبان‌گیری / بازیابی";setOnClickListener{backup()}});r.addView(Button(this).apply{text="گزارش پرداخت‌ها";setOnClickListener{report()}})
  list=LinearLayout(this);list.orientation=LinearLayout.VERTICAL;val sc=ScrollView(this);sc.addView(list);r.addView(sc,LinearLayout.LayoutParams(-1,0,1f));setContentView(r);refresh()}
 fun refresh(){list.removeAllViews();val p=PersianCalendar.academicMonths(start)[idx];list.addView(text("ماه: "+months[idx]+" "+p.first,19f));val ay=start.toString()+"-"+(start+1);db.students().forEach{s->val pay=db.payment(s.id,ay,p.first,p.second);val row=LinearLayout(this);row.orientation=LinearLayout.VERTICAL;row.setPadding(8,5,8,5);row.addView(text(s.name+" — مبلغ: "+s.fee,17f));val cb=CheckBox(this);cb.text=if(pay?.paid==true)"پرداخت شده" else "پرداخت نشده";cb.isChecked=pay?.paid==true;cb.setOnCheckedChangeListener{_,ok->db.setPaid(s.id,ay,p.first,p.second,ok);autoBackup();refresh()};row.addView(cb);if(pay?.paid==true)row.addView(text("تاریخ پرداخت: "+pay.date,14f));list.addView(row)}}
 fun add(){val box=LinearLayout(this);box.orientation=LinearLayout.VERTICAL;val n=EditText(this);n.hint="نام بچه";val f=EditText(this);f.hint="مبلغ ماهانه";f.inputType=2;box.addView(n);box.addView(f);AlertDialog.Builder(this).setTitle("افزودن بچه").setView(box).setPositiveButton("ذخیره"){_,_->if(n.text.isNotBlank()){db.addStudent(n.text.toString().trim(),f.text.toString().toLongOrNull()?:0);autoBackup();refresh()}}.setNegativeButton("انصراف",null).show()}
 fun autoBackup(){getSharedPreferences("backup",0).edit().putString("json",db.exportJson()).apply()}
 fun backup(){AlertDialog.Builder(this).setTitle("پشتیبان‌گیری و بازیابی").setItems(arrayOf("ذخیره فایل پشتیبان","بازیابی از فایل","بازیابی پشتیبان خودکار")){_,w->if(w==0)startActivityForResult(Intent(Intent.ACTION_CREATE_DOCUMENT).apply{type="application/json";putExtra(Intent.EXTRA_TITLE,"school-service-backup.json")},10);if(w==1)startActivityForResult(Intent(Intent.ACTION_OPEN_DOCUMENT).apply{type="application/json";addCategory(Intent.CATEGORY_OPENABLE)},11);if(w==2)getSharedPreferences("backup",0).getString("json",null)?.let{db.restoreJson(it);refresh()}}.show()}
 override fun onActivityResult(r:Int,c:Int,d:Intent?){super.onActivityResult(r,c,d);if(c!=RESULT_OK||d?.data==null)return;try{if(r==10)contentResolver.openOutputStream(d.data!!)?.use{it.write(db.exportJson().toByteArray())};if(r==11)contentResolver.openInputStream(d.data!!)?.bufferedReader()?.use{db.restoreJson(it.readText())};autoBackup();refresh()}catch(e:Exception){Toast.makeText(this,"فایل پشتیبان معتبر نیست",Toast.LENGTH_LONG).show()}}
 fun report(){val ay=start.toString()+"-"+(start+1);val sb=StringBuilder("گزارش سال تحصیلی "+ay+"\n\n");db.students().forEach{s->sb.append(s.name).append("\n");PersianCalendar.academicMonths(start).forEachIndexed{i,p->{val x=db.payment(s.id,ay,p.first,p.second);sb.append(months[i]).append(": ").append(if(x?.paid==true)"پرداخت شده ("+x.date+")" else "پرداخت نشده").append("\n")};sb.append("\n")};AlertDialog.Builder(this).setTitle("گزارش").setMessage(sb.toString()).setPositiveButton("بستن",null).show()}
 override fun onPause(){super.onPause();autoBackup()}
}
